import type { StudioTheme, ThemeColorKey, ThemeFontKey, ThemeFontSizeKey } from './types';

export const themeColorKeys: ThemeColorKey[] = [
  'background',
  'surface',
  'panel',
  'recentPanel',
  'border',
  'primary',
  'primaryText',
  'text',
  'mutedText',
  'warning',
  'danger',
  'editorBackground',
  'editorText',
];

export const themeFontKeys: ThemeFontKey[] = ['interface', 'editor'];

export const themeFontSizeKeys: ThemeFontSizeKey[] = ['interface', 'editor'];

const builtInThemeAuthor = 'Strudel Studio';
const builtInThemeVersion = '1.0.0';
const defaultThemeFonts: StudioTheme['fonts'] = {
  interface: 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  editor: '"Cascadia Code", "Fira Code", Consolas, monospace',
};
const defaultThemeFontSizes: StudioTheme['fontSizes'] = {
  interface: 16,
  editor: 15,
};

type BuiltInThemeColors = Omit<StudioTheme['colors'], 'recentPanel'> & Partial<Pick<StudioTheme['colors'], 'recentPanel'>>;

const createBuiltInTheme = (name: string, colors: BuiltInThemeColors): StudioTheme => ({
  version: 1,
  name,
  author: builtInThemeAuthor,
  themeVersion: builtInThemeVersion,
  colors: {
    recentPanel: colors.panel,
    ...colors,
  },
  fonts: defaultThemeFonts,
  fontSizes: defaultThemeFontSizes,
});

export const defaultStudioTheme: StudioTheme = createBuiltInTheme('Strudel Studio Default', {
  background: '#101312',
  surface: '#171b19',
  panel: '#151917',
  recentPanel: '#121614',
  border: '#28302c',
  primary: '#95d988',
  primaryText: '#10220e',
  text: '#f2f6ef',
  mutedText: '#87938b',
  warning: '#f0ba67',
  danger: '#f26d6d',
  editorBackground: '#0f1211',
  editorText: '#f2f6ef',
});

export const builtInStudioThemes: StudioTheme[] = [
  defaultStudioTheme,
  createBuiltInTheme('Strudel Studio Light', {
    background: '#f6f8f3',
    surface: '#ffffff',
    panel: '#eef3ec',
    border: '#cad4c6',
    primary: '#2f7d55',
    primaryText: '#f7fff8',
    text: '#17211a',
    mutedText: '#68766c',
    warning: '#b46a18',
    danger: '#c93c3c',
    editorBackground: '#ffffff',
    editorText: '#17211a',
  }),
  createBuiltInTheme('Strudel Studio Dark', {
    background: '#0c0d0f',
    surface: '#14161a',
    panel: '#111317',
    border: '#2b3038',
    primary: '#c8d1dc',
    primaryText: '#101216',
    text: '#eef2f6',
    mutedText: '#8e99a8',
    warning: '#d7a84f',
    danger: '#e35d5d',
    editorBackground: '#090a0c',
    editorText: '#eef2f6',
  }),
  createBuiltInTheme('Strudel Studio Blue', {
    background: '#07111f',
    surface: '#0d1d31',
    panel: '#0a1829',
    border: '#1d3b5d',
    primary: '#6bb8ff',
    primaryText: '#031222',
    text: '#eef7ff',
    mutedText: '#87a4bd',
    warning: '#f2bd68',
    danger: '#ff7070',
    editorBackground: '#06101c',
    editorText: '#eef7ff',
  }),
  createBuiltInTheme('Strudel Studio Red', {
    background: '#160708',
    surface: '#250d0f',
    panel: '#1f0b0d',
    border: '#4c1b1f',
    primary: '#ff7a70',
    primaryText: '#250202',
    text: '#fff0ef',
    mutedText: '#b68e8b',
    warning: '#f0b35d',
    danger: '#ff3f3f',
    editorBackground: '#120506',
    editorText: '#fff0ef',
  }),
  createBuiltInTheme('Strudel Studio Yellow', {
    background: '#191406',
    surface: '#27200b',
    panel: '#221b08',
    border: '#4a3c17',
    primary: '#ffd45a',
    primaryText: '#211600',
    text: '#fff7dc',
    mutedText: '#b8a982',
    warning: '#ffb545',
    danger: '#ec5d54',
    editorBackground: '#151004',
    editorText: '#fff7dc',
  }),
  createBuiltInTheme('Strudel Studio Orange', {
    background: '#160e08',
    surface: '#26180e',
    panel: '#201309',
    border: '#51301a',
    primary: '#ff9f4d',
    primaryText: '#241000',
    text: '#fff1e3',
    mutedText: '#b99b82',
    warning: '#ffc069',
    danger: '#f26055',
    editorBackground: '#120a05',
    editorText: '#fff1e3',
  }),
  createBuiltInTheme('Strudel Studio Purple', {
    background: '#100b1d',
    surface: '#1b1230',
    panel: '#170f29',
    border: '#352458',
    primary: '#c59cff',
    primaryText: '#1a0736',
    text: '#f6f0ff',
    mutedText: '#a99abd',
    warning: '#e9b563',
    danger: '#f36f86',
    editorBackground: '#0d0918',
    editorText: '#f6f0ff',
  }),
  createBuiltInTheme('Neon Grove', {
    background: '#0c0b16',
    surface: '#171229',
    panel: '#121f16',
    border: '#2f3d31',
    primary: '#b7ff5c',
    primaryText: '#111907',
    text: '#f4ffe9',
    mutedText: '#94a889',
    warning: '#ffc75c',
    danger: '#ff6f8e',
    editorBackground: '#090912',
    editorText: '#f4ffe9',
  }),
  createBuiltInTheme('Amber Noir', {
    background: '#080807',
    surface: '#15120d',
    panel: '#1e150b',
    border: '#46331c',
    primary: '#ffb000',
    primaryText: '#1d1200',
    text: '#f8f0df',
    mutedText: '#a49a87',
    warning: '#ffd27a',
    danger: '#ff5959',
    editorBackground: '#050505',
    editorText: '#f8f0df',
  }),
  createBuiltInTheme('Tidepool Coral', {
    background: '#071416',
    surface: '#0d2428',
    panel: '#102026',
    border: '#24484f',
    primary: '#6fe7d2',
    primaryText: '#02211d',
    text: '#eafffb',
    mutedText: '#8bacae',
    warning: '#f3b366',
    danger: '#ff7b73',
    editorBackground: '#061012',
    editorText: '#eafffb',
  }),
];
