import { applyStableSliderIds } from './sliderScanner';

export type PlayableStrudelFile = {
  relativePath: string;
  content: string;
  playbackVolume: number;
};

export type CombinedProgramSection = {
  relativePath: string;
  sourceStartLine: number;
  sourceEndLine: number;
};

export type CombinedProgram = {
  code: string;
  sections: CombinedProgramSection[];
};

const normalizeLineEndings = (source: string): string => source.replace(/\r\n/g, '\n').replace(/\r/g, '\n');

const patternLabelPattern = /(^|\n)\s*(?:[A-Za-z_][\w-]*\$|\$)\s*:/g;

const trimTrailingSemicolon = (source: string): string => source.trim().replace(/;\s*$/, '');

const toExpressionSource = (source: string): string => {
  const expression = trimTrailingSemicolon(source);
  return expression.length > 0 ? expression : 'silence';
};

const toWrappableSource = (source: string): string | null => {
  const labelMatches = [...source.matchAll(patternLabelPattern)];
  if (labelMatches.length === 0) {
    return source;
  }

  if (labelMatches.length > 1) {
    return null;
  }

  return source.replace(/(^|\n)(\s*)(?:[A-Za-z_][\w-]*\$|\$)\s*:/, '$1$2');
};

export const combineStrudelFiles = (files: PlayableStrudelFile[]): CombinedProgram => {
  const codeLines: string[] = ['// Generated by Strudel Studio from checked files'];
  const sections: CombinedProgramSection[] = [];

  for (const file of files) {
    const source = applyStableSliderIds(normalizeLineEndings(file.content), file.relativePath);
    const wrappableSource = toWrappableSource(source);
    const canWrap = wrappableSource !== null;
    const sourceLines = (wrappableSource ?? source).length > 0 ? (wrappableSource ?? source).split('\n') : [''];
    codeLines.push('', `// --- ${file.relativePath} ---`);
    const sourceStartLine = canWrap ? codeLines.length + 2 : codeLines.length + 1;

    if (!canWrap) {
      codeLines.push(...sourceLines);
    } else {
      const volume = Number.isFinite(file.playbackVolume) ? file.playbackVolume : 1;
      codeLines.push('$: (');
      codeLines.push(...normalizeLineEndings(toExpressionSource(wrappableSource)).split('\n'));
      codeLines.push(`).gain(${volume})`);
    }

    const sourceEndLine = sourceStartLine + sourceLines.length - 1;
    sections.push({
      relativePath: file.relativePath,
      sourceStartLine,
      sourceEndLine,
    });
  }

  return {
    code: codeLines.join('\n'),
    sections,
  };
};

export const mapCombinedLineToFile = (
  combinedLine: number,
  sections: CombinedProgramSection[],
): { relativePath: string; line: number } | null => {
  const section = sections.find(
    (candidate) => combinedLine >= candidate.sourceStartLine && combinedLine <= candidate.sourceEndLine,
  );

  if (!section) {
    return null;
  }

  return {
    relativePath: section.relativePath,
    line: combinedLine - section.sourceStartLine + 1,
  };
};
