export type PlayableStrudelFile = {
  relativePath: string;
  content: string;
};

export type CombinedProgramSection = {
  relativePath: string;
  sourceStartLine: number;
  sourceEndLine: number;
};

export type CombinedProgram = {
  code: string;
  sections: CombinedProgramSection[];
};

const normalizeLineEndings = (source: string): string => source.replace(/\r\n/g, '\n').replace(/\r/g, '\n');

export const combineStrudelFiles = (files: PlayableStrudelFile[]): CombinedProgram => {
  const codeLines: string[] = ['// Generated by Strudel Studio from checked files'];
  const sections: CombinedProgramSection[] = [];

  for (const file of files) {
    const source = normalizeLineEndings(file.content);
    const sourceLines = source.length > 0 ? source.split('\n') : [''];
    codeLines.push('', `// --- ${file.relativePath} ---`);
    const sourceStartLine = codeLines.length + 1;
    codeLines.push(...sourceLines);
    const sourceEndLine = sourceStartLine + sourceLines.length - 1;
    sections.push({
      relativePath: file.relativePath,
      sourceStartLine,
      sourceEndLine,
    });
  }

  return {
    code: codeLines.join('\n'),
    sections,
  };
};

export const mapCombinedLineToFile = (
  combinedLine: number,
  sections: CombinedProgramSection[],
): { relativePath: string; line: number } | null => {
  const section = sections.find(
    (candidate) => combinedLine >= candidate.sourceStartLine && combinedLine <= candidate.sourceEndLine,
  );

  if (!section) {
    return null;
  }

  return {
    relativePath: section.relativePath,
    line: combinedLine - section.sourceStartLine + 1,
  };
};
