import {
  applyStableSliderIdsWithMap,
  mapStableSliderTransformedOffsetToOriginal,
  type SourceOffsetEdit,
} from './sliderScanner';

export type PlayableStrudelFile = {
  relativePath: string;
  content: string;
  playbackVolume: number;
};

export type CombinedProgramSection = {
  relativePath: string;
  sourceStartLine: number;
  sourceEndLine: number;
  sourceStartOffset: number;
  sourceEndOffset: number;
  offsetEdits: SourceOffsetEdit[];
  wrapperOffsetEdits: SourceOffsetEdit[];
};

export type CombinedProgram = {
  code: string;
  sections: CombinedProgramSection[];
};

type PendingCombinedProgramSection = Omit<CombinedProgramSection, 'sourceStartOffset' | 'sourceEndOffset'>;

const normalizeLineEndings = (source: string): string => source.replace(/\r\n/g, '\n').replace(/\r/g, '\n');

const patternLabelPattern = /(^|\n)\s*(?:[A-Za-z_][\w-]*\$|\$)\s*:/g;

const trimTrailingSemicolon = (source: string): string => source.trim().replace(/;\s*$/, '');

const toExpressionSource = (source: string): string => {
  const expression = trimTrailingSemicolon(source);
  return expression.length > 0 ? expression : 'silence';
};

const toWrappableSource = (source: string): { source: string; offsetEdits: SourceOffsetEdit[] } | null => {
  const labelMatches = [...source.matchAll(patternLabelPattern)];
  if (labelMatches.length === 0) {
    return { source, offsetEdits: [] };
  }

  if (labelMatches.length > 1) {
    return null;
  }

  const match = /(^|\n)(\s*)(?:[A-Za-z_][\w-]*\$|\$)\s*:/.exec(source);
  if (!match) {
    return { source, offsetEdits: [] };
  }

  const prefixLength = (match[1] ?? '').length + (match[2] ?? '').length;
  const originalStart = match.index + prefixLength;
  const originalEnd = match.index + match[0].length;
  const nextSource = source.slice(0, originalStart) + source.slice(originalEnd);

  return {
    source: nextSource,
    offsetEdits: [{
      transformedStart: originalStart,
      transformedEnd: originalStart,
      originalStart,
      originalEnd,
    }],
  };
};

export const combineStrudelFiles = (files: PlayableStrudelFile[]): CombinedProgram => {
  const codeLines: string[] = ['// Generated by Strudel Studio from checked files'];
  const pendingSections: PendingCombinedProgramSection[] = [];

  for (const file of files) {
    const transformed = applyStableSliderIdsWithMap(normalizeLineEndings(file.content), file.relativePath);
    const wrappable = toWrappableSource(transformed.source);
    const canWrap = wrappable !== null;
    const playbackSource = wrappable?.source ?? transformed.source;
    const sourceLines = playbackSource.length > 0
      ? playbackSource.split('\n')
      : [''];
    codeLines.push('', `// --- ${file.relativePath} ---`);
    const sourceStartLine = canWrap ? codeLines.length + 2 : codeLines.length + 1;

    if (!canWrap) {
      codeLines.push(...sourceLines);
    } else {
      const volume = Number.isFinite(file.playbackVolume) ? file.playbackVolume : 1;
      codeLines.push('$: (');
      codeLines.push(...normalizeLineEndings(toExpressionSource(playbackSource)).split('\n'));
      codeLines.push(`).gain(${volume})`);
    }

    const sourceEndLine = sourceStartLine + sourceLines.length - 1;
    pendingSections.push({
      relativePath: file.relativePath,
      sourceStartLine,
      sourceEndLine,
      offsetEdits: transformed.offsetEdits,
      wrapperOffsetEdits: wrappable?.offsetEdits ?? [],
    });
  }

  const code = codeLines.join('\n');
  const lineStartOffsets = getLineStartOffsets(code);
  const sections = pendingSections.map<CombinedProgramSection>((section) => ({
    ...section,
    sourceStartOffset: lineStartOffsets[section.sourceStartLine - 1] ?? code.length,
    sourceEndOffset: getLineEndOffset(code, lineStartOffsets, section.sourceEndLine),
  }));

  return {
    code,
    sections,
  };
};

const getLineStartOffsets = (source: string): number[] => {
  const offsets = [0];

  for (let index = 0; index < source.length; index += 1) {
    if (source[index] === '\n') {
      offsets.push(index + 1);
    }
  }

  return offsets;
};

const getLineEndOffset = (source: string, lineStartOffsets: number[], line: number): number => {
  const nextLineStart = lineStartOffsets[line];
  return nextLineStart === undefined ? source.length : nextLineStart - 1;
};

export const mapCombinedLineToFile = (
  combinedLine: number,
  sections: CombinedProgramSection[],
): { relativePath: string; line: number } | null => {
  const section = sections.find(
    (candidate) => combinedLine >= candidate.sourceStartLine && combinedLine <= candidate.sourceEndLine,
  );

  if (!section) {
    return null;
  }

  return {
    relativePath: section.relativePath,
    line: combinedLine - section.sourceStartLine + 1,
  };
};

export const mapCombinedOffsetRangeToFile = (
  combinedStart: number,
  combinedEnd: number,
  sections: CombinedProgramSection[],
): { relativePath: string; from: number; to: number } | null => {
  const section = sections.find(
    (candidate) =>
      combinedStart >= candidate.sourceStartOffset &&
      combinedStart <= candidate.sourceEndOffset &&
      combinedEnd >= candidate.sourceStartOffset &&
      combinedEnd <= candidate.sourceEndOffset,
  );

  if (!section) {
    return null;
  }

  const transformedStart = combinedStart - section.sourceStartOffset;
  const transformedEnd = combinedEnd - section.sourceStartOffset;
  const stableStart = mapStableSliderTransformedOffsetToOriginal(transformedStart, section.wrapperOffsetEdits);
  const stableEnd = mapStableSliderTransformedOffsetToOriginal(transformedEnd, section.wrapperOffsetEdits);
  const from = mapStableSliderTransformedOffsetToOriginal(stableStart, section.offsetEdits);
  const to = mapStableSliderTransformedOffsetToOriginal(stableEnd, section.offsetEdits);

  if (!Number.isFinite(from) || !Number.isFinite(to) || to <= from) {
    return null;
  }

  return {
    relativePath: section.relativePath,
    from,
    to,
  };
};
